using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("ConsoleMenu")]
[assembly: AssemblyDescription("A console-based menu generator.  Menu items are generated by decorating static methods with [MenuMethod] attributes.  Sub-menus are generated by decorating classes with [MenuClass] attributes.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Simon Elms")]
[assembly: AssemblyProduct("ConsoleMenu")]
[assembly: AssemblyCopyright("Copyright © 2006-2013, 2016 Simon Elms")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("E5B90228-0AFD-4BF1-B28E-0C0780890277")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
